# .github/funding.yml

# Custom checkout URLs
custom: ["https://shipindays.nikhilsai.in"]

# GitHub Sponsors (replace with your GitHub username)
github: [nikhilsaiankilla]

# Common platforms
ko_fi: nikhilsaiankilla
buy_me_a_coffee: nikhilsaiankilla

# Crypto addresses (Example)
# lfx_crowdfunding: 
# open_collective: 
# polar: 
# tide_lift: